/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface InputsInput {
  input: string
  dependencies?: boolean
}
export interface ProjectsInput {
  input: string
  projects: string | Array<string>
}
export function checkObject(input: JsInputs): void
export function callbackReturnPromiseAndSpawn(jsFunc: (arg0: string) => Promise<string>): object
